Add conditional for rendering subFooter
ccswbs/web-components pull request #16
Opened 2024-04-05 16:07 UTC by mmafe

Siteimprove is reporting a Level A issue associated with the footer, due to an empty ul element being rendered. I've added a conditional to check if there are more than 0 elements in the array before rendering the ul element.

<img width="1517" alt="image" src="https://github.com/ccswbs/web-components/assets/1927902/440057be-3213-49bf-b31e-ca615dc61c5c">

2024-04-08 14:59 UTC, RazaMM reviewed
Looks good! Before we merge though, I think its best we set a meeting so that I can explain how we update the npm package as well as how to test it on CH pages before publishing.

2024-04-08 17:14 UTC, mmafe commented
Excellent idea! Let's add this to tomorrow's huddle — that way the whole team can see the process.

2024-04-09 18:58 UTC, mmafe commented
Updated CH environment using **1.2.2-rc.0**: https://mmafe-dev.netlify.app/studentexperience/

2024-04-09 19:16 UTC, RazaMM requested changes
Apparently there was an error with the 1.2.2-rc.0 version I published and its not showing up. I updated the version to 1.2.2-rc.1 and confirmed it is showing up now, so make sure to update on your test site.

2024-04-11 15:42 UTC, mmafe commented
Released as part of #19

2024-04-11 15:42 UTC, closed without merging